remote_theme: samarsault/texture
author: Caden Xu
markdown: kramdown
texture:
  title: Caden Xu
  tagline: Student at Cornell University
  date_format: "%b %-d, %Y"
  showPicker: false
  style: green
  showNav: true
  navigation:
    - title: About
      url: "/about"
