remote_theme: samarsault/texture
author: Caden Xu
markdown: kramdown
kramdown:
    math_engine: katex
texture:
  title: Caden Xu
  tagline: ECE 2027, Cornell University
  date_format: "%b %-d, %Y"
  showPicker: false
  style: green
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"
  social_links:
    github:  cx237
    linkedIn: in/caden-xu-7b34162b9
